  id uuid not null,
  email text not null,
  first_name text null,
  middle_name text null,
  last_name text null,
  phone text null,
  dob date null,
  address_line1 text null,
  address_line2 text null,
  city text null,
  state text null,
  zip text null,
  created_at timestamp with time zone null default now(),
  is_approved boolean null default false,
  license_front_url text null,
  license_back_url text null,
  res_address_line1 text null,
  res_address_line2 text null,
  res_city text null,
  res_state text null,
  res_zip text null,
  mail_address_line1 text null,
  mail_address_line2 text null,
  mail_city text null,
  mail_state text null,
  mail_zip text null,
  constraint users_extended_pkey primary key (id),
  constraint users_extended_email_key unique (email)